### ISSUE TITLE
Refactoring of WindowLocator

### ISSUE THREAD

**Issue by Dalstroem** [Dalstroem/FusionMVVM#30]
In order to make `WindowLocator` more testable and maintainable, it must be refactored.

**Tasks**
- [ ] Move "helper" methods to there own classes.
- [ ] Write better tests for all methods.
- [ ] Use dependency injection (DL).
